// TODO: Copy pasted after compiling with Java we need a better flow here

// File generated by QuickJs4j

export function throwDivideByZero() {
  Calculator_Builtins.throwDivideByZero();
}
export function log(args0) {
  Calculator_Builtins.log(args0);
}
